apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
        - name: {{ .Release.Name }}-postgres
          image: postgres:{{ .Values.postgres.tag }}
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: {{ .Values.postgres.credentials.dbName }}
          - name: POSTGRES_USER
            value: {{ .Values.postgres.credentials.userName }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgres.credentials.userPwd }}