apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: {{ .Release.Name }}-web
          image: {{ .Values.web.image }}:{{ .Values.web.tag }}
          ports:
          - containerPort: 8080
          env:
          - name: DB_DATABASE
            value: {{ .Values.postgres.credentials.dbName }}
          - name: DB_USERNAME
            value: {{ .Values.postgres.credentials.userName }}
          - name: DB_PASSWORD
            value: {{ .Values.postgres.credentials.userPwd }} 
          - name: DB_HOST
            value: {{ .Release.Name }}-postgres