apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sample-app
spec:
  selector:
    app: {{ .Release.Name }}-sample-app
  ports:
  - port: 80
    targetPort: 8080
  type: {{ .Values.app.service.type }}