apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sample-app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-sample-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-sample-app
    spec:
      containers:
      - name: sample-app
        image: {{ .Values.app.image.name }}:{{ .Values.app.image.tag }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080